### ISSUE TITLE
Visible edge around text quads

### ISSUE THREAD

**Issue by rolandhill** [vsg-dev/VulkanSceneGraph#680]
A visible edge can often be seen around the quads for each character when using vsg::Text. The presence of the visible edge is dependent on tilt, zoom and background colour. The image at the top shows the edges more clearly in my own program, while the image at the bottom shows that they are still present in vsgtext (look under the 'en' & 'EN').

![image](https://user-images.githubusercontent.com/2024003/210490616-96568030-8e8d-46df-a0e4-b848659e1f19.png)

![image](https://user-images.githubusercontent.com/2024003/210490194-454fa9ac-2ae7-40c4-a603-ae07d95375d9.png)

To replicate, run vsgtext, then pan, tilt and zoom the image. Try panning to the pink "horizontalAlignment CENTER_ALIGNMENT" text then zooming in. If you zoom too far then the problem disappears and the text looks fine.

Using Kubuntu 22.04, NVidia 3070 Ti.

Regards,
Roland

**Comment by robertosfield** [comment]
This looks like the the glyph quad is picking up texels from neighbouring
glyphs so the margin between them in the texture atlas needs to be
increased,

**Comment by robertosfield** [comment]
@rolandhill  I have begun looking into the issue.  I don't notice any issue on my AMD5700G system with vsgtext, but say similar issues during the development of vsg::Text functionality when the texel_margin between glyphs in the texture atlas wasn't big enough.

Perhaps the filtering on the 3070 Ti must be a bit different and requires a larger texel_margin, or perhaps particular fonts are sensitive to it.  What font are you using?

My thought is to add a entry in vsg::Option to set the texel_margin ratio, currently this ratio is 1/4 of the the glyph size.

**Comment by rolandhill** [comment]
Hi Robert,

I've based my own application on vsgtext, so the text part is almost the
same. I copied times.vsgb from the vsgExamples.

If it is the texel_margin, would you expect problems at the top and bottom
of the glyph in a single line of text?

If you provide the vsg::Option then I can give it a try in the morning.

Regards,
Roland

**Comment by robertosfield** [comment]
I have just checked in the provisional option support into vsgXchange and vsgExamples master:

https://github.com/vsg-dev/vsgXchange/commit/bb2a90dd804ac9ec0879c4142781b3deedd3008b
https://github.com/vsg-dev/vsgExamples/commit/896028a1c14c84176d75c8f6ece72a2443eef1ad

I have tested:

`vsgtext -f ~/Data/OpenSceneGraph-Data/fonts/times.ttf --texel_margin_ratio 0.3`

And for "fun" as it deliberately ruins the rendering by clipping the quads smaller than the outline just to test things:

`vsgtext -f ~/Data/OpenSceneGraph-Data/fonts/fudd.ttf --quad_margin_ratio 0.0`

The default for texel_margin_ratio is 0.25 and quad_margin_ratio is 0.125.  #

The modified vsgXchnage::freetype currently outputs the size of final compute texel_margin and quad_margin that is uses when setting up the texture atlas.

The prebuilt font texture atlas vsgExamples/data/fonts/times.vsgb may need to be rebuilt using revised texel_margin_ratio if it's found that we do need something higher than 0.25.  The downside of having high value the texture atlas will take up more memory.

**Comment by robertosfield** [comment]
@rolandhill Could you try out using vsgXchange master to load a .ttf font and experiment with different texel_margin_ratio and quad_margin_ratio values to see what the lowest values are that give you good results.

The vsgtext example above uses command line parsing support to set the vsg::Options meta data values via the arguments.read(options) call. but you can set this programmatically in your own application using:

    options->setValue(vsgXchange::freetype::texel_margin_ratio, 0.3);
    options->setValue(vsgXchange::freetype::quad_margin_ratio, 0.1);

The larger the texel_margin_ratio the larger the gap between glyphs into the texture atlas so should lead to less issues with the adjacent glyphs bleeding into the rendering. 

A smaller quad_margin_ratio will lead smaller quads being rendered, which can end up clipping outlines and anti-aliasing done but can help avoid the bleeding of adjacent glyphs issue.  If you use wide outlines then you'll need bigger quad margins, but if they are smaller then you might be able to reduce the quad_margin_ratio below the default of 0.125 and not need to increase the texel_margin_ratio.

I hope this makes sense.  Once you have a feel for what values avoids problems then we can rebuild the built into font so that by default we avoid these issues.

**Comment by robertosfield** [comment]
@rolandhill Could you try out using vsgXchange master to load a .ttf font and experiment with different texel_margin_ratio and quad_margin_ratio values to see what the lowest values are that give you good results.

The vsgtext example above uses command line parsing support to set the vsg::Options meta data values via the arguments.read(options) call. but you can set this programmatically in your own application using:

    options->setValue(vsgXchange::freetype::texel_margin_ratio, 0.3);
    options->setValue(vsgXchange::freetype::quad_margin_ratio, 0.1);

The larger the texel_margin_ratio the larger the gap between glyphs into the texture atlas so should lead to less issues with the adjacent glyphs bleeding into the rendering. 

A smaller quad_margin_ratio will lead smaller quads being rendered, which can end up clipping outlines and anti-aliasing done but can help avoid the bleeding of adjacent glyphs issue.  If you use wide outlines then you'll need bigger quad margins, but if they are smaller then you might be able to reduce the quad_margin_ratio below the default of 0.125 and not need to increase the texel_margin_ratio.

I hope this makes sense.  Once you have a feel for what values avoids problems then we can rebuild the built into font so that by default we avoid these issues.

**Comment by rolandhill** [comment]
Hi Robert,

I've been playing around with the glyph margins and have made a few observations. Note that I've pulled new versions of VSG and vsgXchange.

1. Setting the glyph margins via the vsgtext command line worked. I can't see any edge effects using --texel_margin_ratio 0.3 and --quad_margin_ratio 0.19. The output info: text changed when I changed the margin values as expected.

2. Using setValue from c++ has no effect as below;
I used the following code to load times.ttf. Whenever I changed the margin values the text looked just the same and the output info: values were the same. The code below includes a line to read one of the values back into variable tmr and tmr always equals the default of 0.25. I also tested setting the value key directly and got the same result (commented out). So, the command line setValue interface looks to be working, but not the c++ interface.

        _textOptions = vsg::Options::create();
        _textOptions->paths = vsg::getEnvPaths("VSG_FILE_PATH");
        _textOptions->add(vsgXchange::all::create());

        // _textOptions->setValue("texel_margin_ratio", 0.6);
        // _textOptions->setValue("quad_margin_ratio", 0.4);
        _textOptions->setValue(vsgXchange::freetype::texel_margin_ratio, 0.6);
        _textOptions->setValue(vsgXchange::freetype::quad_margin_ratio, 0.4);

        float tmr = vsg::value<float>(0.25f, vsgXchange::freetype::texel_margin_ratio, _textOptions);
        // float tmr = vsg::value<float>(0.25f, "texel_margin_ratio", _textOptions);

        std::string fontpath = siApp::get()->_vsg->fontPath("times.ttf");
        _labelFont = vsg::read_cast<vsg::Font>(fontpath, _textOptions);

3. freetype.h is not included in vsgXchange/all.h, I had to include it specifically. Not sure if this is intended.

Regards,
Roland

**Comment by robertosfield** [comment]
Hi Roland,


On Thu, 5 Jan 2023 at 06:46, Roland Hill ***@***.***> wrote:

> I've been playing around with the glyph margins and have made a few
> observations. Note that I've pulled new versions of VSG and vsgXchange.
>
>    1.
>
>    Setting the glyph margins via the vsgtext command line worked. I can't
>    see any edge effects using --texel_margin_ratio 0.3 and --quad_margin_ratio
>    0.19. The output info: text changed when I changed the margin values as
>    expected.
>
>
That's good news.  Did you find you needed the higher quad_margin_ratio.  I
was expecting you that you could reduce that, and/or just increase the
texel_margin_ratio.



>
>    1.
>    2. Using setValue from c++ has no effect as below;
>
>    I used the following code to load times.ttf. Whenever I changed the
>    margin values the text looked just the same and the output info: values
>    were the same. The code below includes a line to read one of the values
>    back into variable tmr and tmr always equals the default of 0.25. I also
>    tested setting the value key directly and got the same result (commented
>    out). So, the command line setValue interface looks to be working, but not
>    the c++ interface.
>
>     _textOptions = vsg::Options::create();
>     _textOptions->paths = vsg::getEnvPaths("VSG_FILE_PATH");
>     _textOptions->add(vsgXchange::all::create());
>
>     // _textOptions->setValue("texel_margin_ratio", 0.6);
>     // _textOptions->setValue("quad_margin_ratio", 0.4);
>     _textOptions->setValue(vsgXchange::freetype::texel_margin_ratio, 0.6);
>     _textOptions->setValue(vsgXchange::freetype::quad_margin_ratio, 0.4);
>
>     float tmr = vsg::value<float>(0.25f, vsgXchange::freetype::texel_margin_ratio, _textOptions);
>     // float tmr = vsg::value<float>(0.25f, "texel_margin_ratio", _textOptions);
>
>     std::string fontpath = siApp::get()->_vsg->fontPath("times.ttf");
>     _labelFont = vsg::read_cast<vsg::Font>(fontpath, _textOptions);
>
>
>
My best guess is that the setValue calls are passing in doubles, so mapping
to a doubleValue rather than the floatValue, and the freetype ReaderWriter
is checking for a float.

Could you try add a f to make sure it's a float passed in.:

 _textOptions->setValue(vsgXchange::freetype::texel_margin_ratio, 0.6f);
 _textOptions->setValue(vsgXchange::freetype::quad_margin_ratio, 0.4f);



>
>    1.
>    2.
>
>    freetype.h is not included in vsgXchange/all.h, I had to include it
>    specifically. Not sure if this is intended.
>
>
vsgXchange should check for freetype and if it finds it by default build
the vsgXchange::freetype.  I haven't seen anything other than this
behaviour in all my testing so I don't know what might be up.

When you say you have to include it specifically, what did you do?

**Comment by rolandhill** [comment]
Hi Robert,

1.
An increase to quad_margin_ratio was necessary and it looks to be the main contributor to the edge effects. If you set quad_margin_ratio to 0.19 and leave texel_margin_ratio at 0.25 then you only get the very occasional flickers of edge effects, but still noticable. At 0.30 I can't see any problems.

2.
I just figured out the problem with passing in a double and requesting back a float! Yes, adding the f fixes it.

3.
I had to put
#include <vsgXchange/freetype.h>

in my source file. Otherwise, vsgXchange::freetype::texel_margin_ratio is not recognised. If I comment out the lines with vsgXchange::freetype::* then I don't need the include.

Cheers,
Roland

**Comment by robertosfield** [comment]
1. OK, so provisionally I could change the default of texel_margin_ratio to 0.3 and quad_margin_ratio to 0.19 and things will look good for you?  I can create a branch for these changes and get your to test these branches.

2. W.r.t double vs float, I would like to have support for converting double to float and visa versa, though that's another topic for another day.

3. Adding #include <vsgXchange/freetype.h> to use vsgXchange::freetype::texel_margin_ratio is what I would have expected so everything is OK there.  Using the straight "texel_margin_ratio" instead avoids this but is a little more prone to changes to vsgXchange.

**Comment by robertosfield** [comment]
I have updated vsgExamples/data/fonts/times.vsgb and times.vsgt with the texel_margin_ratio to 0.3 and quad_margin_ratio to 0.19:

https://github.com/vsg-dev/vsgExamples/commit/08bbdd2ec3bd00056d9f1180d1e127ee5bafeae0

@rolandhill could you test and let me know how you get on.

**Comment by rolandhill** [comment]
That's vastly improved. I'm still seeing a couple of issues though.
![image](https://user-images.githubusercontent.com/2024003/210885240-8c4d542f-a61d-46ac-bea6-75179410bce3.png)
![image](https://user-images.githubusercontent.com/2024003/210885278-255b3729-30d1-421e-a751-8a9e4f4a79ce.png)

I have to bump it up to texel_margin_ratio = 0.4 and quad_margin_ratio = 0.22 to get rid of them.

How do you produce a font.vsgb file from a font.ttf?

Cheers,
Roland

**Comment by robertosfield** [comment]
It's the large quad_margin_ratio that will be causing these artifacts.  I have reduced the quad_margin_ratio to 0.15 and left the texel_margin_ratio at 0.3.  This is checked into the vsgXchange font_margin_changes branch and updated times.vsgb is cheked into vsgExamples/data master.

**Comment by rolandhill** [comment]
Those changes just take it back to the original problem for me.

Just looking into what else it can be and it looks to be a draw order / blending problem. I've modified vsgtext to draw a textured quad in the background. The tests below use your latest versions as per your last message.

If I draw the quad first then the edges are nearly absent (you can just see a bit to the top right of the SDF)
![image](https://user-images.githubusercontent.com/2024003/211132612-e76932f6-bb94-4532-80d0-c17abdaa4c39.png)

If I draw the quad last, then the edges are quite prominent when zoomed out, but disappear when zoomed in.
![image](https://user-images.githubusercontent.com/2024003/211132538-37fccb25-2e92-4f13-abfe-0435c9b847cb.png)

I initially discounted it being draw order because I thought it should then affect the entire character background instead of just the edges. Is the text supposed to be under a depthsort?

The modified vsgtext is attached.
[vsgtext.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/10365562/vsgtext.zip)

**Comment by robertosfield** [comment]
Text is alpha blended so they should be drawn after elements like terrain, you needn't place them in the depth sorted bin if they just appear in the scene graph after the terrain etc.

I wonder if it looks so bad on your system because those edge fragments aren't being discarded as they have a slightly above 0 value.  Perhaps tweaking the alpha discard in the text fragment shader might help.

**Comment by robertosfield** [comment]
@rolandhill, I have merged your modified vsgtext.cpp and tweaked a little to allow me to run with --before or --after on the command line to enable the different positions of the background.  When I see the zoom out I can see the artifacts when I run with --after.  This is partly expected as blended text should come after opaque objects in the scene graph to ensure blending.  If the text is embedded in a subgraph that contains both opaque and blending objects then decorating with a vsg::DepthSorted node would be appropriate.

However, I still think the might be stuff we can do in the shader to discard fragment from neighboring quads, and around the edges of fonts to do a better job in the incorrectly ordered set up.

$ git diff
diff --git a/examples/text/vsgtext/vsgtext.cpp b/examples/text/vsgtext/vsgtext.cpp
index caee64a..4dbaa64 100644
--- a/examples/text/vsgtext/vsgtext.cpp
+++ b/examples/text/vsgtext/vsgtext.cpp
@@ -61,7 +61,9 @@ vsg::ref_ptr<vsg::Node> createQuad(const vsg::vec3& origin, const vsg::vec3& hor
     // set up search paths to SPIRV shaders and textures
     vsg::Paths searchPaths = vsg::getEnvPaths("VSG_FILE_PATH");
 
-    auto textureData = convertToRGBA.convert(sourceData);
+    vsg::Path textureFile("textures/lz.vsgb");
+    auto textureData = vsg::read_cast<vsg::Data>(vsg::findFile(textureFile, searchPaths));
+    // auto textureData = convertToRGBA.convert(sourceData);
     if (!textureData) return {};
 
     // load shaders
@@ -549,6 +551,16 @@ int main(int argc, char** argv)
         scenegraph->addChild(dynamic_text);
     }
 
+    auto quad = createQuad(vsg::vec3(-3.0, 1.0, -15.0), vsg::vec3(20.0, 0.0, 0.0), vsg::vec3(0.0, 0.0, 20.0));
+    if (arguments.read("--before"))
+    {
+        scenegraph->children.insert(scenegraph->children.begin(), quad);
+    }
+    else if (arguments.read("--after"))
+    {
+        scenegraph->children.push_back(quad);
+    }
+
     if (!output_filename.empty())
     {
         vsg::write(scenegraph, output_filename);

**Comment by robertosfield** [comment]
My current thought is that it would be worth experimenting with the discard in the text.frag, which currently just discards fragments with an alpha of zero:

    if (outColor.a == 0.0) discard;

**Comment by robertosfield** [comment]
I have tweak the vsgtext example to allow us to override the shaders in the text ShaderSet using the --rs command line option, along with the --after and --before command line options mentioned above for creating the background.

https://github.com/vsg-dev/vsgExamples/tree/text_experiment

I have modified the text.frag discard to:

    if (outColor.a < 0.15) discard;

With this change I can run:

   vsgtext --rs --after

And I don't see the problem outline. @rolandhill could you have a look at the results of this changes with --rs.

I'm not happy with a discard value of 0.15 so I'm not about to check this in as new shader for text.  My preference would be to change the sampling of the textures so that the edges of the quad are automatically set to have an alpha of 0 to avoid the bleed in from neighboring glyphs.

**Comment by rolandhill** [comment]
With vsgtext --rs --after I still see some outlines, but it is greatly improved
![image](https://user-images.githubusercontent.com/2024003/211180643-bb41cf4e-e06c-452a-a446-ee715188d9a1.png)

for comparison, below is the result of vsgtext --after (no --rs)
![image](https://user-images.githubusercontent.com/2024003/211180677-2a2d7a50-4dc8-4715-be55-4fd333796e79.png)

Note that there are still a few problems with vsgtext --before. At some zoom levels there are minor lines - look at the 'o' and 't' of 'support'. They are still present with vsgtext --rs --before, although maybe a bit reduced.
![image](https://user-images.githubusercontent.com/2024003/211180715-9c8654ef-fa11-4428-bcb4-c6e5955ec508.png)

**Comment by robertosfield** [comment]
I spent some time today experimenting with vsgtext and the associated
shaders to explore what might be going on and my current feeling is that
text.frag shader isn't handling outlines well in the case of minification
and this is causing ghost lines to appear set back from certain edges.

I don't know the cause of this issue, I've only got as far as homing in on
where the problem might be.  This issue doesn't look to be caused by the
texel or quad margin, but is influenced by them.  I'm hoping once the
fragment shader is refined further we'll not need to use such large margins.

However, as I haven't found the specific cause yet I don't know how easy it
will be to resolve it.  I will tinker further through this week. In the
meantime putting text at the end of the scene graph or underneath
vsg::DepthSorted node should hit the worst artefact caused by this problem.

**Comment by rolandhill** [comment]
Thanks for looking at it, Robert. At least we are closer to understanding
what causes it.

Roland

**Comment by robertosfield** [comment]
I have just checked in a fix to the text shaders that address a problem with the depth offset being the wrong sign, this should fix an issue with glyphs being overlapped by the previous glyph which should help with blending of adjacent glyphs.  This particular regression was caused by adopting reverse depth buffer in the VSG by default but missing the change in sign of this offset.

https://github.com/vsg-dev/vsgExamples/commit/f54e2fc781046bf07876ad50799f87ef485c0417
